### ISSUE TITLE
How should we navigate away from the search results and return to the regular list of students?

### ISSUE THREAD

**Issue by ConMur** [Qwe1rty/Event-Planner#4]
I was thinking of adding a "Normal View" or "Clear Search" button but im not sure if that would be the best

**Comment by sunmatthew** [comment]
i can think of 2 ways
1. when you click the search button and search, the search button changes to a clear search button
2. instead of a search button we make it a search field that just updates the table (this way won't look as good b/c of the current design)
so basically, the first way is for a better looking UI, but slightly harder for users to use, and the the second way is for an easier to use program, but a worse looking UI

**Comment by ConMur** [comment]
I think option 1 would be best

**Comment by sunmatthew** [comment]
okok

**Comment by Qwe1rty** [comment]
What I was thinking of is that it would automatically update the search for every character inputted (kinda like how google's instant search thing works). Then, if you wanted to clear the search you'd just clear the search box. I imagine the search function is fairly fast since there wouldn't ever be over 2000 students anyway

**Comment by ConMur** [comment]
If we did that then we would have to change the UI from a search button to a search bar.  It would not be too hard to do.

**Comment by sunmatthew** [comment]
is that what we're going with?

**Comment by ConMur** [comment]
If its possible I think it would look good

**Comment by sunmatthew** [comment]
do we have a general search function that just searches for any keyword in all students

**Comment by Qwe1rty** [comment]
The search is limited to a single parameter, if that's what you mean(?)

**Comment by sunmatthew** [comment]
yeah i think it would be good if we could do a search that doesn't take any parameters

**Comment by Qwe1rty** [comment]
I think we've got a finalized search layout now, so I'll close this
